#
# https://blog.bitsrc.io/vs-codes-rest-client-plugin-is-all-you-need-to-make-api-calls-e9e95fcfd85a
#

GET http://127.0.0.1:6060/api/messages/public
Content-Type: application/json

###

GET http://127.0.0.1:6060/api/messages/public
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlhObGNhR094b0pHU2hhSTFMTmtPZyJ9.eyJpc3MiOiJodHRwczovL2Rldi13NzAyemVmenYyMzA3dXRrLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJJVU40OWZVSkNzemRWbE42WTQwbGtoa3lJRGJjV1BuOEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9oZWxsby13b3JsZC5leGFtcGxlLmNvbSIsImlhdCI6MTczMzk0NTU4OCwiZXhwIjoxNzM0MDMxOTg4LCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJJVU40OWZVSkNzemRWbE42WTQwbGtoa3lJRGJjV1BuOCJ9.bxP7ZWLZT_uk3IA-9xK3_lEDqN1e14k0lduLd8oRSjtmVqkdWVTeccL3FRryFnvgedkC5ObsP2yvYTJnToCAIWzEMZlyUBd8V9palpunIK3PFePFJ8DSOdsy3eKKoqTWc5MVwxlSgMy-YPwJyR1t5Z-OluAPwVooNDEDnVJUAD8MZ-IXbwvwJxl_URUtee2zP9io-ngqkC47QMRMiLj5ywLizFKUWPYyPPuEjPg-bO3q0hJDYY7URpZGU2rHtER1g5mi5pj9yvdvzNwoVrdfJZxIjBNjwatu6wa-uaPSwdd9g9RJAVOVOixV1J-jwMQkb5SnyXpsO8tURmKiVJ29ug

###

GET http://127.0.0.1:6060/api/messages/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlhObGNhR094b0pHU2hhSTFMTmtPZyJ9.eyJpc3MiOiJodHRwczovL2Rldi13NzAyemVmenYyMzA3dXRrLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJJVU40OWZVSkNzemRWbE42WTQwbGtoa3lJRGJjV1BuOEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9oZWxsby13b3JsZC5leGFtcGxlLmNvbSIsImlhdCI6MTczMzk0NTU4OCwiZXhwIjoxNzM0MDMxOTg4LCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJJVU40OWZVSkNzemRWbE42WTQwbGtoa3lJRGJjV1BuOCJ9.bxP7ZWLZT_uk3IA-9xK3_lEDqN1e14k0lduLd8oRSjtmVqkdWVTeccL3FRryFnvgedkC5ObsP2yvYTJnToCAIWzEMZlyUBd8V9palpunIK3PFePFJ8DSOdsy3eKKoqTWc5MVwxlSgMy-YPwJyR1t5Z-OluAPwVooNDEDnVJUAD8MZ-IXbwvwJxl_URUtee2zP9io-ngqkC47QMRMiLj5ywLizFKUWPYyPPuEjPg-bO3q0hJDYY7URpZGU2rHtER1g5mi5pj9yvdvzNwoVrdfJZxIjBNjwatu6wa-uaPSwdd9g9RJAVOVOixV1J-jwMQkb5SnyXpsO8tURmKiVJ29ug

###

GET http://127.0.0.1:6060/api/messages/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlhObGNhR094b0pHU2hhSTFMTmtPZyJ9.eyJpc3MiOiJodHRwczovL2Rldi13NzAyemVmenYyMzA3dXRrLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJJVU40OWZVSkNzemRWbE42WTQwbGtoa3lJRGJjV1BuOEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9oZWxsby13b3JsZC5leGFtcGxlLmNvbSIsImlhdCI6MTczMzk0NTU4OCwiZXhwIjoxNzM0MDMxOTg4LCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJJVU40OWZVSkNzemRWbE42WTQwbGtoa3lJRGJjV1BuOCJ9.bxP7ZWLZT_uk3IA-9xK3_lEDqN1e14k0lduLd8oRSjtmVqkdWVTeccL3FRryFnvgedkC5ObsP2yvYTJnToCAIWzEMZlyUBd8V9palpunIK3PFePFJ8DSOdsy3eKKoqTWc5MVwxlSgMy-YPwJyR1t5Z-OluAPwVooNDEDnVJUAD8MZ-IXbwvwJxl_URUtee2zP9io-ngqkC47QMRMiLj5ywLizFKUWPYyPPuEjPg-bO3q0hJDYY7URpZGU2rHtER1g5mi5pj9yvdvzNwoVrdfJZxIjBNjwatu6wa-uaPSwdd9g9RJAVOVOixV1J-jwMQkb5SnyXpsO8tURmKiVJ29ug

###

GET http://127.0.0.1:6060/api/messages/invalid
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlhObGNhR094b0pHU2hhSTFMTmtPZyJ9.eyJpc3MiOiJodHRwczovL2Rldi13NzAyemVmenYyMzA3dXRrLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJJVU40OWZVSkNzemRWbE42WTQwbGtoa3lJRGJjV1BuOEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9oZWxsby13b3JsZC5leGFtcGxlLmNvbSIsImlhdCI6MTczMzk0NTU4OCwiZXhwIjoxNzM0MDMxOTg4LCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJJVU40OWZVSkNzemRWbE42WTQwbGtoa3lJRGJjV1BuOCJ9.bxP7ZWLZT_uk3IA-9xK3_lEDqN1e14k0lduLd8oRSjtmVqkdWVTeccL3FRryFnvgedkC5ObsP2yvYTJnToCAIWzEMZlyUBd8V9palpunIK3PFePFJ8DSOdsy3eKKoqTWc5MVwxlSgMy-YPwJyR1t5Z-OluAPwVooNDEDnVJUAD8MZ-IXbwvwJxl_URUtee2zP9io-ngqkC47QMRMiLj5ywLizFKUWPYyPPuEjPg-bO3q0hJDYY7URpZGU2rHtER1g5mi5pj9yvdvzNwoVrdfJZxIjBNjwatu6wa-uaPSwdd9g9RJAVOVOixV1J-jwMQkb5SnyXpsO8tURmKiVJ29ug

###

GET http://127.0.0.1:6060/api/messages/protected
Content-Type: application/json
Authorization: Bearer invalidtoken1234567890

